-- MySQL Script generated by MySQL Workbench
-- ter 06 ago 2024 15:12:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema dbEcommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbEcommerce` ;

-- -----------------------------------------------------
-- Schema dbEcommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbEcommerce` ;
USE `dbEcommerce` ;

-- -----------------------------------------------------
-- Table `dbEcommerce`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEcommerce`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(80) NOT NULL,
  `name` VARCHAR (80) NOT NULL,
  `desc` VARCHAR(255) NULL,
  `quantityProducts` INT(3),
  `price` DECIMAL(10,2) NOT NULL,
  `discountedPrice` DECIMAL(10,2) NOT NULL,
  `numberInstallments` INT(2),
  `valueInstallments` DECIMAL(10,2),
  `img` LONGTEXT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEcommerce`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEcommerce`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `saltPassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEcommerce`.`Client`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `Client` ;

CREATE TABLE IF NOT EXISTS `dbEcommerce`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `socialName` VARCHAR(80) NULL,
  `name` VARCHAR(80) NOT NULL,
  `fone` VARCHAR (15) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `saltPassword` VARCHAR(255) NOT NULL,
  `birthDate` DATE NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `ST` VARCHAR(2) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `neighborhood` VARCHAR(100) NOT NULL,
  `complement` VARCHAR(60) NULL,
  `number` VARCHAR(15) NOT NULL,
  `street` VARCHAR(80) NOT NULL,
  `token` INT,
  PRIMARY KEY (`idClient`),
  INDEX `cpf` (`CPF` ASC) VISIBLE,
  INDEX `email_cpf` (`Email` ASC, `CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEcommerce`.`Sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEcommerce`.`Sell` (
  `idSell` INT NOT NULL AUTO_INCREMENT,
  `sellDate` DATETIME NOT NULL,
  `client_idClient` INT NOT NULL,
  `paymentMethod` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSell`),
  INDEX `fk_Sell_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Sell_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `dbEcommerce`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEcommerce`.`ProductCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEcommerce`.`ProductCart` (
  `product_idProduct` INT NOT NULL,
  `sell_idSell` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`Product_idProduct`, `Sell_idSell`),
  INDEX `fk_Product_has_Sell_Sell1_idx` (`Sell_idSell` ASC) VISIBLE,
  INDEX `fk_Product_has_Sell_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Sell_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `dbEcommerce`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Sell_Sell1`
    FOREIGN KEY (`Sell_idSell`)
    REFERENCES `dbEcommerce`.`Sell` (`idSell`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





